"use client";
import {useMemo,useState} from "react";
type Duty={s:string;t:string;a:string;d:string;n:number;w:string;x:string;u:string;applies:(p:Profile)=>boolean};
type Profile={place:string;form:string;activity:string;revenue:number;vat:string;staff:number;ubo:string;related:string;crossBorder:string};
const all:Duty[]=[
 {s:"Action required",t:"VAT return and payment",a:"Federal Tax Authority",d:"28 Aug 2026",n:15,w:"The fictional company is VAT registered and its sample tax period closes before this filing date.",x:"Reconcile sales and purchases, review recoverable input tax and prepare the return.",u:"https://tax.gov.ae/en/taxes/Vat.aspx",applies:p=>p.vat==="Registered"},
 {s:"Review required",t:"VAT registration threshold",a:"Federal Tax Authority",d:"31 Aug 2026",n:18,w:"The sample revenue is above the mandatory-registration threshold while the profile says the company is not registered.",x:"Review taxable supplies and registration timing with the FTA or a tax adviser.",u:"https://tax.gov.ae/en/taxes/Vat.aspx",applies:p=>p.vat!=="Registered"&&p.revenue>=375000},
 {s:"Due soon",t:"Trade licence renewal",a:"Licensing authority",d:"18 Sep 2026",n:36,w:"The fictional licence anniversary falls within the 90-day monitoring window.",x:"Confirm tenancy documentation, licensed activities and renewal requirements.",u:"https://www.dubaidet.gov.ae/",applies:p=>true},
 {s:"Monitoring",t:"Corporate Tax record review",a:"Federal Tax Authority",d:"30 Sep 2026",n:48,w:"The company is within the UAE Corporate Tax regime and should maintain supporting records.",x:"Review ledger completeness, tax adjustments and supporting documentation.",u:"https://tax.gov.ae/en/taxes/corporate.tax.aspx",applies:p=>true},
 {s:"Monitoring",t:"Beneficial-owner register check",a:"Licensing authority",d:"18 Oct 2026",n:66,w:"Covered legal persons should keep beneficial-owner information current when changes occur.",x:"Confirm ownership, control and nominee information remains accurate.",u:"https://uaelegislation.gov.ae/en/legislations/2176",applies:p=>p.form!=="Sole Establishment"},
 {s:"Review required",t:"Beneficial-owner update review",a:"Licensing authority",d:"20 Aug 2026",n:7,w:"The demonstration profile indicates changed, uncertain or missing beneficial-owner information.",x:"Confirm the change event and update the relevant register and authority filing where required.",u:"https://uaelegislation.gov.ae/en/legislations/2176",applies:p=>p.ubo!=="Filed — no recent changes"&&p.form!=="Sole Establishment"},
 {s:"Monitoring",t:"Employment and payroll records",a:"MOHRE",d:"31 Oct 2026",n:79,w:"The sample company has employees and should maintain current employment and payroll records.",x:"Check contracts, work permits, payroll evidence and expiry dates.",u:"https://www.mohre.gov.ae/",applies:p=>p.staff>0&&!["DIFC","ADGM"].includes(p.place)},
 {s:"Monitoring",t:"Free-zone status and substance review",a:"Federal Tax Authority",d:"15 Oct 2026",n:63,w:"The profile is a free-zone entity, so conditions relevant to its Corporate Tax treatment should be monitored.",x:"Review qualifying activities, non-qualifying revenue, substance and audited financial-statement requirements.",u:"https://tax.gov.ae/en/taxes/corporate.tax.aspx",applies:p=>p.place.includes("Free Zone")||p.form==="Free Zone Company"},
 {s:"Review required",t:"Related-party transaction review",a:"Federal Tax Authority",d:"30 Sep 2026",n:48,w:"The fictional profile indicates transactions with owners, connected persons or related entities.",x:"Identify related parties, document terms and review transfer-pricing requirements.",u:"https://tax.gov.ae/en/taxes/corporate.tax.aspx",applies:p=>p.related==="Yes"},
 {s:"Monitoring",t:"Cross-border tax documentation",a:"Federal Tax Authority",d:"30 Sep 2026",n:48,w:"The sample company records cross-border transactions that may require additional tax and supporting-document review.",x:"Review counterparties, transaction purpose, withholding implications and transfer-pricing support.",u:"https://tax.gov.ae/en/taxes/corporate.tax.aspx",applies:p=>p.crossBorder==="Yes"}
];
const initial:Profile={place:"Dubai Mainland",form:"Limited Liability Company",activity:"Business consultancy",revenue:750000,vat:"Registered",staff:12,ubo:"Filed — no recent changes",related:"No",crossBorder:"Yes"};
export default function Home(){
 const [screen,setScreen]=useState("home"),[step,setStep]=useState(0),[item,setItem]=useState<Duty|null>(null),[p,setP]=useState(initial);
 const duties=useMemo(()=>all.filter(x=>x.applies(p)).sort((a,b)=>a.n-b.n),[p]);
 const act=duties.filter(x=>x.s.includes("required")).length,soon=duties.filter(x=>x.s==="Due soon").length;
 const set=(k:keyof Profile,v:string|number)=>setP({...p,[k]:v});
 const steps=[
  <><label>Licensing location<select value={p.place} onChange={e=>set("place",e.target.value)}><option>Dubai Mainland</option><option>Abu Dhabi Mainland</option><option>DMCC Free Zone</option><option>IFZA Free Zone</option><option>DIFC</option><option>ADGM</option></select></label><label>Legal form<select value={p.form} onChange={e=>set("form",e.target.value)}><option>Limited Liability Company</option><option>Free Zone Company</option><option>Sole Establishment</option><option>Branch</option></select></label><label>Primary activity<select value={p.activity} onChange={e=>set("activity",e.target.value)}><option>Business consultancy</option><option>Trading</option><option>E-commerce</option><option>Technology services</option><option>Professional services</option></select></label></>,
  <><label>Estimated annual revenue (AED)<input type="number" value={p.revenue} onChange={e=>set("revenue",Number(e.target.value))}/></label><label>VAT status<select value={p.vat} onChange={e=>set("vat",e.target.value)}><option>Registered</option><option>Not registered</option><option>Registration in progress</option></select></label><label>Related-party transactions?<select value={p.related} onChange={e=>set("related",e.target.value)}><option>No</option><option>Yes</option><option>Not sure</option></select></label></>,
  <><label>Number of employees<input type="number" value={p.staff} onChange={e=>set("staff",Number(e.target.value))}/></label><label>Beneficial-owner filing<select value={p.ubo} onChange={e=>set("ubo",e.target.value)}><option>Filed — no recent changes</option><option>Filed — details changed</option><option>Not sure</option><option>Not filed</option></select></label><label>Cross-border transactions?<select value={p.crossBorder} onChange={e=>set("crossBorder",e.target.value)}><option>No</option><option>Yes</option><option>Not sure</option></select></label></>
 ];
 return <main><Header go={setScreen}/>
 {screen==="home"&&<section className="hero"><div><p className="eyebrow">UAE Compliance Intelligence · Demonstration</p><h1>Know what applies.<br/><em>Know what’s due.</em></h1><p className="lead">From an indicative UAE setup estimate to a personalised compliance plan, practical next actions and a clear 90-day view—linked to authoritative sources.</p><div className="buttons"><button className="primary" onClick={()=>setScreen("setup")}>Estimate setup & compliance →</button><button onClick={()=>{setStep(0);setScreen("assessment")}}>Check obligations</button></div><small>No account required · No data is saved · Use fictional information only</small></div><aside className="snapshot"><div className="snaphead">PERSONALISED OUTLOOK <b>13 AUG — 11 NOV</b></div><div className="health"><strong>{duties.length}</strong><span>applicable items<br/><em>{act||1} requires attention</em></span></div>{duties.slice(0,3).map(x=><Mini key={x.t} x={x}/>)}</aside></section>}
 {screen==="setup"&&<SetupCalculator continueTo={()=>{setStep(0);setScreen("assessment")}}/>}
 {screen==="assessment"&&<section className="assessment"><div><p className="eyebrow">Company assessment</p><h2>Build the company profile</h2><p>Change the fictional profile and see the obligation set adapt. Nothing is stored.</p><ol>{["Company structure","Tax profile","People & ownership"].map((x,i)=><li key={x} className={i===step?"on":i<step?"done":""}><span>{i<step?"✓":i+1}</span>{x}</li>)}</ol><div className="safe"><b>Safe demonstration</b><p>Do not enter a real company name, licence number, owner name, Emirates ID or financial records.</p></div></div><article className="form"><div className="progress"><i style={{width:`${(step+1)*33.34}%`}}/></div><small>STEP {step+1} OF 3</small><h3>{["Where does the business operate?","Set the demonstration tax profile","Complete the operating profile"][step]}</h3>{steps[step]}<footer className="formbuttons"><button disabled={!step} onClick={()=>setStep(step-1)}>← Back</button><button className="primary" onClick={()=>step<2?setStep(step+1):setScreen("results")}>{step<2?"Continue →":"Check what applies →"}</button></footer></article></section>}
 {screen==="results"&&<Results p={p} duties={duties} go={setScreen}/>}
 {(screen==="dashboard"||screen==="calendar"||screen==="changes")&&<section className="workspace"><WorkHead p={p} go={setScreen}/><div className="workspace-tabs"><button className={screen==="dashboard"?"selected":""} onClick={()=>setScreen("dashboard")}>Overview</button><button className={screen==="calendar"?"selected":""} onClick={()=>setScreen("calendar")}>Calendar</button><button className={screen==="changes"?"selected":""} onClick={()=>setScreen("changes")}>Regulatory changes</button></div><div className="stats"><Stat l="Action required" v={act} n="review now" danger/><Stat l="Due soon" v={soon} n="within 60 days"/><Stat l="Monitoring" v={duties.length-act-soon} n="no immediate action"/><Stat l="Next deadline" v={duties[0]?.n||0} n="days remaining"/></div>
 {screen==="dashboard"?<div className="grid"><article className="panel"><PanelHead title="What needs attention" action={()=>setScreen("calendar")}/>{duties.map(x=><DutyRow key={x.t} x={x} open={setItem}/>)}</article><Reserve/></div>:screen==="calendar"?<Calendar duties={duties} open={setItem}/>:<Changes p={p}/>}</section>}
 {screen==="assistant"&&<Assistant duties={duties} go={setScreen}/>}
 {screen==="adviser"&&<AdviserWorkspace go={setScreen}/>}
 {screen==="pricing"&&<Pricing go={setScreen}/>}
 {screen==="platform"&&<PlatformCentre/>}
 {item&&<Modal x={item} close={()=>setItem(null)}/>}<SiteFoot/></main>
}
function Header({go}:{go:(s:string)=>void}){return <header><button className="brand" onClick={()=>go("home")}><i>م</i><b>Mizan</b><small>UAE REGULATORY INTELLIGENCE</small></button><nav><button onClick={()=>go("setup")}>Setup calculator</button><button className="active" onClick={()=>go("dashboard")}>Compliance</button><button onClick={()=>go("assistant")}>Ask Mizan</button><button onClick={()=>go("adviser")}>For advisers</button><button onClick={()=>go("platform")}>Platform</button><button onClick={()=>go("pricing")}>Pricing</button></nav><span className="demo">DEMO · FICTIONAL DATA</span></header>}
function Mini({x}:{x:Duty}){return <div className="mini"><i className={x.s.includes("required")?"red":""}/><span><b>{x.t}</b><small>{x.d} · {x.a}</small></span></div>}
function WorkHead({p,go}:{p:Profile;go:(s:string)=>void}){return <div className="workhead"><div><p className="eyebrow">Fictional company profile</p><h2>Al Noor Advisory LLC</h2><p>{p.place} · {p.form} · {p.activity} · {p.staff} employees</p></div><button onClick={()=>go("assessment")}>Edit sample profile</button></div>}
function Stat({l,v,n,danger=false}:{l:string;v:number;n:string;danger?:boolean}){return <article><span>{l}</span><b className={danger?"danger":""}>{v}</b><small>{n}</small></article>}
function PanelHead({title,action}:{title:string;action:()=>void}){return <div className="panelhead"><div><p className="eyebrow">90-day intelligence</p><h3>{title}</h3></div><button onClick={action}>View calendar →</button></div>}
function DutyRow({x,open}:{x:Duty;open:(x:Duty)=>void}){return <button className="duty" onClick={()=>open(x)}><span className={x.s.includes("required")?"tag urgent":"tag"}>{x.s}</span><div><b>{x.t}</b><small>{x.a}</small></div><div className="date"><b>{x.d}</b><small>{x.n} days</small></div><i>›</i></button>}
function Results({p,duties,go}:{p:Profile;duties:Duty[];go:(s:string)=>void}){return <section className="workspace results-page"><p className="eyebrow">Applicability assessment complete</p><h2>{duties.length} items identified</h2><p className="results-lead">Based on the fictional {p.place} {p.form.toLowerCase()} profile. These results demonstrate how structured answers drive rule-based outcomes.</p><div className="result-summary"><div><b>{duties.filter(x=>x.s.includes("required")).length}</b><span>Require review</span></div><div><b>{duties.filter(x=>x.s==="Due soon").length}</b><span>Due soon</span></div><div><b>{duties.filter(x=>x.s==="Monitoring").length}</b><span>Monitor</span></div></div><article className="panel">{duties.map(x=><div className="result-line" key={x.t}><span className={x.s.includes("required")?"tag urgent":"tag"}>{x.s}</span><div><b>{x.t}</b><p>{x.w}</p></div></div>)}</article><div className="buttons"><button className="primary" onClick={()=>go("dashboard")}>Open 90-day dashboard →</button><button onClick={()=>go("assessment")}>Change answers</button></div></section>}
function Reserve(){return <aside className="panel reserve"><p className="eyebrow">Tax reserve planner</p><h3>Indicative reserve</h3><div className="ring"><b>AED 18,750</b><small>illustrative estimate</small></div><dl><div><dt>Estimated taxable profit</dt><dd>AED 400,000</dd></div><div><dt>Illustrative tax</dt><dd>AED 4,500</dd></div><div><dt>Current sample reserve</dt><dd>AED 2,000</dd></div></dl><p className="fine">Planning demonstration only. Not a tax calculation or advice.</p></aside>}
function Calendar({duties,open}:{duties:Duty[];open:(x:Duty)=>void}){return <article className="panel calendar"><p className="eyebrow">Personalised compliance calendar</p><h3>August — November 2026</h3>{["Aug","Sep","Oct","Nov"].map(m=><div className="month" key={m}><b>{({Aug:"August",Sep:"September",Oct:"October",Nov:"November"} as any)[m]}</b><div>{duties.filter(x=>x.d.includes(m)).map(x=><button key={x.t} onClick={()=>open(x)}><span>{x.d.split(" ")[0]}</span><div><b>{x.t}</b><small>{x.a}</small></div></button>)}{!duties.some(x=>x.d.includes(m))&&<p className="empty-month">No identified sample deadlines</p>}</div></div>)}</article>}
function Changes({p}:{p:Profile}){return <article className="panel changes"><p className="eyebrow">Regulatory change monitor</p><h3>Changes relevant to this profile</h3><div className="change"><span>MONITORING</span><div><b>UAE e-invoicing readiness</b><p>Potential future impact for UAE businesses. The demonstration would track official implementation dates, scope and required actions.</p><small>Profile match · {p.activity} · Federal</small></div></div><div className="change"><span>REVIEWED</span><div><b>Corporate Tax guidance library</b><p>The sample company is matched to Corporate Tax guidance based on its entity and revenue profile.</p><small>Last demonstration review · 13 Aug 2026</small></div></div><aside className="notice"><b>How production monitoring will work</b><p>Detected source changes enter a review queue. Customers are notified only after the effective date, affected profiles and required action are confirmed.</p></aside></article>}
function Modal({x,close}:{x:Duty;close:()=>void}){return <div className="modal" onClick={close}><article onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><span className={x.s.includes("required")?"tag urgent":"tag"}>{x.s}</span><h2>{x.t}</h2><p>{x.a} · Due {x.d}</p><section><b>Why this appears</b><p>{x.w}</p></section><section><b>Recommended next action</b><p>{x.x}</p></section><a href={x.u} target="_blank" rel="noreferrer">View official source ↗</a><p className="fine">Demonstration using fictional data. Confirm current requirements with the authority or a qualified adviser.</p></article></div>}
function SetupCalculator({continueTo}:{continueTo:()=>void}){const [zone,setZone]=useState("Mainland");const [visas,setVisas]=useState(2);const [office,setOffice]=useState("Flexi desk");const base=zone==="Mainland"?14500:zone==="Dubai Free Zone"?12500:9500;const visa=visas*3800;const workspace=office==="Private office"?24000:office==="Flexi desk"?6500:0;const total=base+visa+workspace;return <section className="setup-page"><div className="setup-copy"><p className="eyebrow">Free setup calculator</p><h2>Plan the first year—not just the licence.</h2><p>Explore an illustrative setup range and see which continuing compliance areas a new UAE business should plan for.</p><div className="safe"><b>Illustrative demonstration</b><p>These are sample figures, not quotations or current authority fees. Actual costs depend on activity, authority, approvals, office, visas and service providers.</p></div></div><article className="setup-card"><label>Jurisdiction type<select value={zone} onChange={e=>setZone(e.target.value)}><option>Mainland</option><option>Dubai Free Zone</option><option>Other UAE Free Zone</option></select></label><label>Sample visas: <b>{visas}</b><input type="range" min="0" max="6" value={visas} onChange={e=>setVisas(Number(e.target.value))}/></label><label>Workspace<select value={office} onChange={e=>setOffice(e.target.value)}><option>No workspace</option><option>Flexi desk</option><option>Private office</option></select></label><div className="estimate"><span>Illustrative first-year range</span><strong>AED {(total*.9).toLocaleString()}–{(total*1.15).toLocaleString()}</strong><small>Licence, sample visas and selected workspace only</small></div><div className="cost-lines"><p><span>Setup and licence assumption</span><b>AED {base.toLocaleString()}</b></p><p><span>Visa assumption</span><b>AED {visa.toLocaleString()}</b></p><p><span>Workspace assumption</span><b>AED {workspace.toLocaleString()}</b></p></div><div className="ongoing"><b>Plan for continuing obligations</b><span>Corporate Tax</span><span>VAT assessment</span><span>Licence renewal</span><span>UBO records</span></div><button className="primary full" onClick={continueTo}>Build my sample compliance plan →</button></article></section>}
function Assistant({duties,go}:{duties:Duty[];go:(s:string)=>void}){
 const [q,setQ]=useState("Why does VAT return appear?");
 const [answer,setAnswer]=useState("");
 const [loading,setLoading]=useState(false);
 const [error,setError]=useState("");
 const selected=q.includes("VAT")?duties.find(x=>x.t.includes("VAT")):q.includes("beneficial")?duties.find(x=>x.t.includes("Beneficial")):duties[0];
 const ask=async(question:string)=>{
  setQ(question);setAnswer("");setError("");setLoading(true);
  try{
   const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question})});
   const payload=await response.json() as {answer?:string;error?:string};
   if(!response.ok) throw new Error(payload.error||"The assistant is unavailable.");
   setAnswer(payload.answer||"");
  }catch(caught){setError(caught instanceof Error?caught.message:"The assistant is unavailable.");}
  finally{setLoading(false);}
 };
 return <section className="assistant-page"><div className="assistant-head"><p className="eyebrow">AI compliance assistant · NVIDIA-backed</p><h2>Ask about the rule result—not guesswork.</h2><p>The assistant explains structured compliance outcomes and keeps the final decision with you and your adviser.</p></div><div className="assistant-grid"><aside><b>Suggested questions</b>{["Why does VAT return appear?","What should I do about beneficial ownership?","What is my next deadline?"].map(x=><button key={x} className={q===x?"picked":""} onClick={()=>ask(x)}>{x}</button>)}</aside><article className="conversation"><div className="user-bubble">{q}</div><div className="ai-bubble"><span>م</span><div>{loading?<p>Checking the configured NVIDIA assistant…</p>:answer?<><b>NVIDIA assistant</b><p>{answer}</p></>:selected?<><b>{selected.t}</b><p>{selected.w}</p><p><strong>Suggested action:</strong> {selected.x}</p><a href={selected.u} target="_blank" rel="noreferrer">Open the official source ↗</a></>:<p>The current fictional profile did not trigger that item.</p>}{error&&<p className="fine">{error} Showing the structured result above instead.</p>}</div></div><div className="answer-guard"><b>Decision boundary</b><p>This assistant provides information, not legal or tax advice. Confirm current requirements with the relevant authority or a qualified adviser.</p></div><button className="primary" onClick={()=>go("dashboard")}>Return to dashboard</button></article></div></section>}
const clients=[{name:"Al Noor Advisory LLC",place:"Dubai Mainland",due:"VAT return · 15 days",risk:"Action required",tasks:2},{name:"Nexa Digital FZCO",place:"DMCC Free Zone",due:"CT records · 21 days",risk:"Review required",tasks:3},{name:"Crescent Retail LLC",place:"Abu Dhabi Mainland",due:"Licence renewal · 32 days",risk:"Due soon",tasks:1},{name:"Harbour Design FZE",place:"IFZA Free Zone",due:"UBO review · 47 days",risk:"Monitoring",tasks:0},{name:"Atlas Trading LLC",place:"Dubai Mainland",due:"VAT return · 52 days",risk:"Monitoring",tasks:1}];
function AdviserWorkspace({go}:{go:(s:string)=>void}){const [filter,setFilter]=useState("All");const shown=filter==="All"?clients:clients.filter(x=>x.risk===filter);return <section className="adviser-page"><div className="adviser-hero"><div><p className="eyebrow">Mizan Adviser · Demonstration</p><h2>Every client deadline, one clear view.</h2><p>Designed for accountants, tax advisers and corporate-service providers managing multiple UAE entities.</p></div><button className="primary" onClick={()=>go("pricing")}>View adviser plan →</button></div><div className="portfolio-stats"><Stat l="Fictional clients" v={clients.length} n="sample portfolio"/><Stat l="Action needed" v={2} n="across two clients" danger/><Stat l="Open tasks" v={7} n="team workload"/><Stat l="Due in 30 days" v={2} n="portfolio deadlines"/></div><article className="client-panel"><div className="client-head"><div><p className="eyebrow">Client portfolio</p><h3>Compliance overview</h3></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Action required</option><option>Review required</option><option>Due soon</option><option>Monitoring</option></select></div><div className="client-table"><div className="client-row labels"><span>Client</span><span>Next item</span><span>Status</span><span>Tasks</span></div>{shown.map(c=><button className="client-row" key={c.name} onClick={()=>go("dashboard")}><span><b>{c.name}</b><small>{c.place}</small></span><span>{c.due}</span><span className={c.risk.includes("required")?"tag urgent":"tag"}>{c.risk}</span><span className="task-count">{c.tasks}</span></button>)}</div></article><div className="adviser-features"><article><b>Portfolio deadlines</b><p>Prioritise upcoming obligations across all managed entities.</p></article><article><b>Client task requests</b><p>Request documents and track completion without email chains.</p></article><article><b>Rule-version history</b><p>See which verified rule produced each outcome and when it changed.</p></article></div></section>}
function Pricing({go}:{go:(s:string)=>void}){return <section className="pricing-page"><div className="pricing-head"><p className="eyebrow">Illustrative commercial model</p><h2>Start free. Pay when compliance becomes ongoing.</h2><p>Pricing shown only to test product positioning; no checkout or subscription is enabled.</p></div><div className="plans"><Plan name="Free" price="AED 0" desc="For initial discovery" features={["Setup calculator","One company assessment","Limited 90-day preview","Official-source links"]} action="Try calculator" click={()=>go("setup")}/><Plan featured name="Business" price="AED 149" desc="per month · illustrative" features={["Full compliance calendar","Regulatory-change alerts","Tasks and evidence","Tax-reserve planner","Ask Mizan explanations"]} action="Explore business demo" click={()=>go("dashboard")}/><Plan name="Adviser" price="AED 499+" desc="per month · illustrative" features={["Multi-client portfolio","Team task management","Client document requests","Bulk onboarding","Future accounting integrations"]} action="View adviser workspace" click={()=>go("adviser")}/></div><aside className="pricing-note"><b>Recommended validation strategy</b><p>Test willingness to pay with accountants first. One adviser account may bring dozens of SME entities, reducing acquisition cost and generating better rule-quality feedback.</p></aside></section>}
function Plan({name,price,desc,features,action,click,featured=false}:{name:string;price:string;desc:string;features:string[];action:string;click:()=>void;featured?:boolean}){return <article className={featured?"plan featured":"plan"}>{featured&&<span className="recommended">RECOMMENDED</span>}<p className="eyebrow">{name}</p><h3>{price}</h3><small>{desc}</small><ul>{features.map(x=><li key={x}><span>✓</span>{x}</li>)}</ul><button className={featured?"primary":""} onClick={click}>{action} →</button></article>}
const ruleRows=[{id:"VAT-RET-01",name:"VAT return and payment",authority:"FTA",version:"v1.4",review:"Verified",date:"13 Aug 2026"},{id:"CT-REC-02",name:"Corporate Tax record review",authority:"FTA",version:"v1.2",review:"Verified",date:"12 Aug 2026"},{id:"UBO-REG-01",name:"Beneficial-owner register check",authority:"MOET",version:"v2.1",review:"Verified",date:"10 Aug 2026"},{id:"LIC-REN-01",name:"Trade licence renewal",authority:"Licence authority",version:"v1.0",review:"Jurisdiction review",date:"08 Aug 2026"},{id:"EMP-REC-01",name:"Employment and payroll records",authority:"MOHRE",version:"v1.1",review:"Verified",date:"06 Aug 2026"},{id:"EINV-MON-01",name:"E-invoicing readiness monitor",authority:"MOF",version:"v0.3",review:"Monitoring",date:"13 Aug 2026"}];
function PlatformCentre(){const [tab,setTab]=useState("rules"),[search,setSearch]=useState("");const rows=ruleRows.filter(r=>(r.name+r.id+r.authority).toLowerCase().includes(search.toLowerCase()));return <section className="platform-page"><div className="platform-head"><div><p className="eyebrow">Platform operations · Demonstration</p><h2>The controls behind every answer.</h2><p>Rule governance, source traceability and integration boundaries designed for defensible compliance intelligence.</p></div><div className="control-score"><strong>6</strong><span>sample rules<br/><i>5 reviewed</i></span></div></div><div className="platform-tabs"><button className={tab==="rules"?"selected":""} onClick={()=>setTab("rules")}>Verified rules library</button><button className={tab==="audit"?"selected":""} onClick={()=>setTab("audit")}>Review queue</button><button className={tab==="integrations"?"selected":""} onClick={()=>setTab("integrations")}>Integrations & API</button></div>{tab==="rules"?<article className="rule-panel"><div className="rule-toolbar"><div><p className="eyebrow">Structured obligations</p><h3>Rules library</h3></div><input placeholder="Search rules…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="rule-table"><div className="rule-row labels"><span>Rule</span><span>Authority</span><span>Version</span><span>Status</span><span>Last reviewed</span></div>{rows.map(r=><div className="rule-row" key={r.id}><span><b>{r.name}</b><small>{r.id}</small></span><span>{r.authority}</span><span>{r.version}</span><span className={r.review==="Verified"?"verified":"reviewing"}>{r.review}</span><span>{r.date}</span></div>)}</div></article>:tab==="audit"?<ReviewQueue/>:<Integrations/>}</section>}
function ReviewQueue(){return <div className="review-grid"><article className="rule-panel"><p className="eyebrow">Change review queue</p><h3>3 items awaiting assessment</h3>{[{s:"New source detected",t:"E-invoicing guidance update",a:"Assess scope and effective date"},{s:"Source changed",t:"FTA Corporate Tax guide",a:"Compare against current rule version"},{s:"Periodic review",t:"Dubai licence renewal rule",a:"Confirm authority-specific requirements"}].map(x=><div className="review-item" key={x.t}><span>{x.s}</span><div><b>{x.t}</b><small>{x.a}</small></div><i>Pending</i></div>)}</article><aside className="governance"><p className="eyebrow">Publishing gate</p><h3>Human review required</h3><ol><li><span>1</span>Detect official-source change</li><li><span>2</span>Compare and assess impact</li><li><span>3</span>Update rule conditions</li><li><span>4</span>Approve and version</li><li><span>5</span>Notify affected profiles</li></ol><p className="fine">No detected change is automatically converted into customer advice.</p></aside></div>}
function Integrations(){const systems=[{n:"Xero",d:"Import chart-of-accounts and reporting-period signals",stage:"Planned"},{n:"QuickBooks",d:"Read accounting-period and transaction summaries",stage:"Planned"},{n:"Zoho Books",d:"Support UAE SME bookkeeping workflows",stage:"Planned"},{n:"Mizan API",d:"Deliver obligations and deadline intelligence to partners",stage:"Design"}];return <div className="integration-layout"><article className="rule-panel"><p className="eyebrow">Accounting integrations</p><h3>Connect signals—not judgement.</h3><p className="integration-lead">Future integrations would provide structured company and accounting signals. The Mizan rules engine would remain responsible for applicability logic.</p>{systems.map(s=><div className="integration" key={s.n}><div className="integration-mark">{s.n.slice(0,2).toUpperCase()}</div><div><b>{s.n}</b><small>{s.d}</small></div><span>{s.stage}</span></div>)}</article><aside className="api-card"><p className="eyebrow">Compliance API</p><h3>One profile. Structured outcomes.</h3><pre>{`POST /v1/assessments
{
  "jurisdiction": "dubai_mainland",
  "entity_type": "llc",
  "vat_status": "registered"
}

→ obligations[]
→ deadlines[]
→ source_versions[]`}</pre><div className="api-boundary"><b>Production boundary</b><p>Consent, data minimisation, authentication, audit logs, rate limits and contractual API terms would be required before launch.</p></div></aside></div>}
function SiteFoot(){return <footer className="sitefoot"><b>Mizan</b><p>Demonstration regulatory data tool for informational product validation only. Not legal, tax or accounting advice.</p><span>Fictional data · August 2026</span></footer>}
